### ISSUE TITLE
Error when defining a user-defined capacity

### ISSUE THREAD

**Issue by ajipratama14** [OSeMOSYS/osemosys_global#181]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

Hi, I was trying to put an inter-connector between two regions in Indonesia: IDNJW (Java region-Indonesia) and IDNSL (Sulawesi region - Indonesia). What I did was I define the user_defined_capacity by adding the following line:
   TRNIDNJWIDNSL: [2, 2040]
  TRNIDNSMIDNKA: [1, 2030]
  
  Unfortunately, I got an error as depicted below:
  
<img width="950" alt="error 4" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/b2765ddc-1b2b-4d17-ba64-1109ee24602f">
[powerplant.log](https://github.com/user-attachments/files/15833060/powerplant.log)

Do you know why this issue exists?

### Steps To Reproduce

1. Running the command
2. Modify the config file to include the user-defined capacity
3. Run the snakemake again

### Operating System

Linux

### Log output

```shell
INFO:Can not set dtype for InputActivityRatio on VALUE
INFO:Can not set dtype for CapitalCost on VALUE
INFO:Can not set dtype for FixedCost on VALUE
INFO:Can not set dtype for TotalTechnologyModelPeriodActivityUpperLimit on VALUE
INFO:Can not set dtype for OperationalLife on VALUE
INFO:Can not set dtype for TotalAnnualMaxCapacityInvestment on VALUE
INFO:Can not set dtype for TotalAnnualMinCapacityInvestment on VALUE
Traceback (most recent call last):
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1886, in <module>
    main()
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1267, in main
    user_defined_capacity(region_name, years, output_data_dir, tech_capacity, op_life_dict)
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1521, in user_defined_capacity
    tech_capacity_dict[tech] = tech_params[2]
                               ~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by maartenbrinkerink** [comment]
Hi @ajipratama14. Can you try changing the config entries to include all user_defined_capacity parameters as below;

user_defined_capacity:
  # technology: [capacity, 
  #              first_year, 
  #              "fixed/open", 
  #              first_year_of_expansion, 
  #              build_rate_per_year, 
  #              cost]

So for your example it could be;

TRNIDNJWIDNSL: [0, 2020, "open", 2040, 2, 800]
TRNIDNSMIDNKA: [0, 2020, "open", 2030, 1, 800]

This is assuming your lines are expansion candidates with 2030/2040 the first year that they can be build. If they are fixed values existing by a given year then the below is more appropriate;

TRNIDNJWIDNSL: [2, 2040, "open", 2020, 0, 0]
TRNIDNSMIDNKA: [1, 2030, "open", 2020, 0, 0]

Note that the 800 for cost is purely an indicative value. For custom entries it's up to the user to define the inputs. 

Let me know if this works!

**Comment by ajipratama14** [comment]
Hi @maartenbrinkerink ,

Thank you for your answer.

I tried your suggestion and unfortunately I still got the same error. The attached files show the log details.
[powerplant.log](https://github.com/user-attachments/files/15838332/powerplant.log)
[timeslice.log](https://github.com/user-attachments/files/15838333/timeslice.log)

Also, this is the snapshot of my config file:
<img width="661" alt="Error 5" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/89d3734b-8a2e-4aa4-8d8b-4e470ce081e1">

Did I do something wrong with the input?

PS: I also tried to do the BBIN_connector example and it also didn't work either.

Thanks!!

**Comment by maartenbrinkerink** [comment]
Just to be clear, if you don't add any user_defined_capacities the model runs fine? Could you share your config file so I can have a look?

**Comment by ajipratama14** [comment]
Yes, everything works just fine if I don't add any user_defined_capacities. Sure, I attached both config files: Without any user defined capacities (working) and with user defined capacities (not-working). Sorry, I can't upload it with YAML format as github doesn't allow such format, so I convert it into JSON file as attached. Thanks!
[config_with user defined.json](https://github.com/user-attachments/files/15839612/config_with.user.defined.json)
[config.json](https://github.com/user-attachments/files/15839613/config.json)

**Comment by trevorb1** [comment]
Hi @ajipratama14; thanks for submitting (another!) issue!  

Unfortunately, I was not able to recreate your issue; the `config_with_user_defined` ran fine on my computer. Are you able to please print out `tech_capacity` in the user defined constraints section of `powerplant_data.py` to check that the variable is being read correctly from your config file.

Please add this in at line `1515`

```python
print(tech_capacity)
```

The output should look something like this: 

```bash 
$ python workflow/scripts/osemosys_global/powerplant_data.py
INFO:Can not set dtype for InputActivityRatio on VALUE
INFO:Can not set dtype for CapitalCost on VALUE
INFO:Can not set dtype for FixedCost on VALUE
INFO:Can not set dtype for TotalTechnologyModelPeriodActivityUpperLimit on VALUE
INFO:Can not set dtype for OperationalLife on VALUE
INFO:Can not set dtype for TotalAnnualMaxCapacityInvestment on VALUE
INFO:Can not set dtype for TotalAnnualMinCapacityInvestment on VALUE
{'TRNIDNJWIDNSL': [0, 2020, 'open', 2040, 2, 800], 'TRNIDNSMIDNKA': [0, 2020, 'open', 2030, 1, 800]}
INFO:Powerplant Data Created
```

**Comment by ajipratama14** [comment]
Hi @trevorb1, thank you so much for helping me again!

I encountered an issue when trying to print tech_capacity. The output is shown below:
<img width="917" alt="Error 6" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/e66785d5-86fa-453b-a987-6ab98ed9ba03">

I suspect this issue might be related to the version of miniconda3 I am using. Previously, I faced problems with the latest version of miniconda3, and switching to an older version resolved those issues. However, this specific problem with user_defined_capacity persists.

Thanks!!

**Comment by trevorb1** [comment]
hmm... are you using the same environment as before; as this is now a dependency issue on `osemosys_global`? Moreover, it looks like you are running through Windows. Are you able to try running through WSL (or on a UNIX system), as that is what we have been testing on. Links to how to install WSL can be found [here](https://osemosys-global.readthedocs.io/en/latest/installation.html#installation). 

Thanks for the patience while we work through these issues!

**Comment by ajipratama14** [comment]
Ah my bad! I just tried to run the environment through WSL. Here is the result.
<img width="910" alt="Error 7" src="https://github.com/OSeMOSYS/osemosys_global/assets/145935831/a0ad2476-900d-4dda-8548-dd72e670d215">

The following error showed up:
(osemosys-global) (base) root@IC-5CG22076FP:~/osemosys_global# /root/miniconda3/envs/osemosys-global/bin/python /root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py
INFO:Can not set dtype for InputActivityRatio on VALUE
INFO:Can not set dtype for CapitalCost on VALUE
INFO:Can not set dtype for FixedCost on VALUE
INFO:Can not set dtype for TotalTechnologyModelPeriodActivityUpperLimit on VALUE
INFO:Can not set dtype for OperationalLife on VALUE
INFO:Can not set dtype for TotalAnnualMaxCapacityInvestment on VALUE
INFO:Can not set dtype for TotalAnnualMinCapacityInvestment on VALUE
{'TRNIDNJWIDNSL': [0, 2020, 'open', 2040, 2, 800], 'TRNIDNSMIDNKA': [0, 2020, 'open', 2030, 1, 800]}
Traceback (most recent call last):
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1886, in <module>
    main()
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1267, in main
    user_defined_capacity(region_name, years, output_data_dir, tech_capacity, op_life_dict)
  File "/root/osemosys_global/workflow/scripts/osemosys_global/powerplant_data.py", line 1535, in user_defined_capacity
    tech_set = tech_set.append(pd.DataFrame({'VALUE':[each_tech]}))
               ^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

**Comment by ajipratama14** [comment]
Hi @trevorb1 ,

I changed line 1535 with this code:
tech_set = pd.concat([tech_set, new_row], ignore_index=True)

It seems to solve the issue. Did I change it correctly?

**Comment by trevorb1** [comment]
Hey @ajipratama14. Thanks for the updates! I noticed the same issue as you and made the update in [this commit](https://github.com/OSeMOSYS/osemosys_global/commit/eac736a1cf44e3aff2e1049471eb04e4ffdb8ae5) this morning. DId you want to pull the master branch changes and try your run again?

**Comment by ajipratama14** [comment]
Thanks!! I didn't notice the latest update. Unfortunately, there is an error due to the visualization. Do you know why?

Here is the log details:
Traceback (most recent call last):
  File "/root/osemosys_global/workflow/scripts/osemosys_global/visualise.py", line 415, in <module>
    main(input_data, result_data, scenario_figs_dir, cost_line_expansion_xlsx, countries, results_by_country, years)
  File "/root/osemosys_global/workflow/scripts/osemosys_global/visualise.py", line 62, in main
    plot_transmission_capacity(cost_line_expansion_xlsx, result_data, scenario_figs_dir, year)
  File "/root/osemosys_global/workflow/scripts/osemosys_global/visualise.py", line 242, in plot_transmission_capacity
    trn['line_width'] = (scaler.fit_transform(trn[['VALUE']]) * maxlinewidth).round(1)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 295, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/base.py", line 1098, in fit_transform
    return self.fit(X, **fit_params).transform(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 450, in fit
    return self.partial_fit(X, y)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/base.py", line 1474, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/preprocessing/_data.py", line 490, in partial_fit
    X = self._validate_data(
        ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1072, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1)) while a minimum of 1 is required by MinMaxScaler.
[visualisation.log](https://github.com/user-attachments/files/15844434/visualisation.log)

**Comment by trevorb1** [comment]
Hmm... You are still running the same configuration file as you attached before?

**Comment by ajipratama14** [comment]
Yes, I used the attached config file. Do you encounter the same issue?
[config_new.json](https://github.com/user-attachments/files/15844813/config_new.json)

**Comment by trevorb1** [comment]
Hey @ajipratama14; thanks for attaching the config file! Since `IDN` comes with custom data (see `resources/data/custom_nodes/` folder, this was causing an issue with plotting tranmsission capacity. 

I fixed this in PR #182 and moved this to a separate issue ticket #183. If you pull the latest master branch and run the workflow again, hopefully it should work!

**Comment by trevorb1** [comment]
Im gonna close this issue now, as I believe the issue has been addressed in [this comment](https://github.com/OSeMOSYS/osemosys_global/issues/181#issuecomment-2168763693). If you are still experiencing UDC issues, @ajipratama14, please reopen this issue. :)
