### ISSUE TITLE
[BUG] Error in rule summarise_results & visualisation

### ISSUE THREAD

**Issue by user-pg** [OSeMOSYS/osemosys_global#240]
### Conda environment check

- [X] I have tried using the `osemosys-global` conda environment.

### Current Behavior

Hi, very new to OG. I've just installed OG and am going through Example 1 here [https://osemosys-global.readthedocs.io/en/latest/getting-started.html#project-overview](url). But summarise_results table and visualisations executions fail. Both logs say: ModuleNotFoundError: No module named 'osemosys_global.powerplant_data'

### Expected Behavior

I would expect both these jobs to execute successfully.

### Steps To Reproduce

Follow installation instructions here [https://osemosys-global.readthedocs.io/en/latest/installation.html](url). Git Repo cloned approx 5 PM GMT Nov. 28th. 

### Operating System

MacOS

### Log output

```shell
Traceback (most recent call last):
  File "/Users/user/osemosys_global/workflow/scripts/osemosys_global/visualise.py", line 10, in <module>
    from osemosys_global.visualisation.utils import get_color_codes, get_map, plot_map_trn_line, plot_map_text, load_node_data_demand_center
  File "/opt/miniconda3/envs/osemosys-global/lib/python3.11/site-packages/osemosys_global/visualisation/utils.py", line 11, in <module>
    from osemosys_global.powerplant_data import format_transmission_name
ModuleNotFoundError: No module named 'osemosys_global.powerplant_data'
```

**Comment by maartenbrinkerink** [comment]
Welcome @user-pg! Sorry for the late reply, but I've made some updates to the visualisation scripts that should solve this. Could you pull the latest version of the `master` branch and rerun your workflow to test it out?
